Rigtch/rigtch-fm-www

- src/components/footer.tsx
- src/hooks/auth.tsx
- src/layouts/default.tsx
> feat(components): add footer to layout

- .github/workflows/main.yml
- .vscode/settings.json
> 6 ci configuration

- README.md
> docs(README.md): add stacks deployment info and description

- src/components/last-tracks-section.tsx
- src/components/top-tracks/section.tsx
- src/components/track-card.tsx
- src/graphql/queries/top-tracks.ts
- src/graphql/types/track.ts
- src/pages/index.tsx
> feat(top-tracks): add top tracks section

- src/components/playback/card.tsx
- src/hooks/api/use-playback-state.ts
> 35 fix playback card

- src/api/fetchers/get-last-tracks.spec.ts
- src/api/fetchers/get-playback-state.spec.ts
- src/api/fetchers/get-profile.spec.ts
- src/api/fetchers/get-top-artists.spec.ts
- src/api/fetchers/get-top-tracks.spec.ts
- src/components/element/card.spec.tsx
- src/components/element/top-one-card.spec.tsx
- src/components/footer.spec.tsx
- src/components/playback/card.spec.tsx
- src/components/playback/card.tsx
- src/components/profile/card.spec.tsx
- src/components/profile/info.spec.tsx
- src/components/utils/relative-time.spec.tsx
- src/hooks/api/use-last-tracks.spec.tsx
- src/hooks/api/use-profile.spec.tsx
- src/hooks/api/use-top-artists.spec.tsx
- src/hooks/api/use-top-tracks.spec.tsx
- src/sections/home/last-tracks.spec.tsx
- src/sections/home/top-artists.spec.tsx
- src/sections/home/top-genres.spec.tsx
- src/sections/home/top-tracks.spec.tsx
- tests/mocks/album.ts
- tests/mocks/artist.ts
- tests/mocks/index.ts
- tests/mocks/profile.ts
- tests/mocks/track.ts
> 45 add missing component tests

- src/components/element/card.tsx
- src/components/utils/relative-time.tsx
> feat(card): responsive on small devices

- src/components/connect/button.tsx
- src/components/connect/card.tsx
- src/components/connect/discord-card.tsx
- src/components/connect/steps.tsx
- src/pages/about.tsx
> feat(about): add whats rigtch card and discord connect card

- src/components/element/card.spec.tsx
- src/components/element/card.tsx
- src/components/element/top-one-card.tsx
- src/sections/home/top-artists.tsx
- src/sections/home/top-tracks.tsx
> feat(top-tracks): same look as top artists

- src/api/constants/errors.ts
- src/api/constants/index.ts
- src/api/fetchers/get-last-tracks.spec.ts
- src/api/fetchers/get-last-tracks.ts
- src/api/fetchers/get-playback-state.spec.ts
- src/api/fetchers/get-top-artists.spec.ts
- src/api/fetchers/get-top-artists.ts
- src/api/fetchers/get-top-genres.spec.ts
- src/api/fetchers/get-top-genres.ts
- src/api/fetchers/get-top-tracks.spec.ts
- src/api/fetchers/get-top-tracks.ts
- src/pages/index.tsx
- src/pages/not-registered.tsx
> 52 create page for not registered users

- src/components/profile/card.tsx
- src/components/profile/info.tsx
> fix(components/profile): display first letter of `displayName` if user has no profile image

- src/components/select-time-range.tsx
> refactor(components/select-time-range): reverse items

- src/components/element/card.tsx
- src/components/element/top-one-card.tsx
> feat(element/top-one-card): remove stars from image

- src/components/element/card.tsx
- src/components/element/top-one-card.tsx
> feat(images): change alt text to album name if its a track

- src/components/playback/card.tsx
- src/components/profile/card.tsx
> feat(profile/card): fix gaps and adjust text size

- src/components/common/infinite-loading-button.tsx
- src/components/navigation-bar.tsx
- src/components/profile/info.tsx
> refactor(components/navigation-bar): use `Menubar` component

- src/api/fetchers/get-last-tracks.ts
- src/api/hooks/use-analysis.tsx
- src/api/hooks/use-last-tracks.tsx
- src/api/hooks/use-playback-state.tsx
- src/api/hooks/use-profile.tsx
- src/api/hooks/use-toggle-playback-state.tsx
- src/api/hooks/use-top-artists.tsx
- src/api/hooks/use-top-genres.tsx
- src/api/hooks/use-top-tracks.tsx
- src/components/profile/info.tsx
- src/hooks/use-auth-cookies.spec.tsx
- src/hooks/use-auth-cookies.tsx
- src/middleware.spec.ts
- src/middleware.ts
> fix(middleware): redirect after refreshing token

- src/components/element/card-skeleton.tsx
- src/components/element/card.tsx
- src/components/element/top-one-card-skeleton.tsx
- src/components/element/top-one-card.tsx
- src/components/views/top-artists.tsx
- src/components/views/top-tracks.tsx
- src/pages/profile/top-artists.tsx
- src/pages/profile/top-tracks.tsx
- src/sections/profile/top-artists.tsx
- src/sections/profile/top-genres.tsx
- src/sections/profile/top-tracks.tsx
> feat(profile): add skeleton when changing time range

- src/components/element/index.ts
- src/components/item/card/index.spec.tsx
- src/components/item/card/index.tsx
- src/components/item/card/skeleton.tsx
- src/components/item/card/types/index.ts
- src/components/item/card/types/item-card-base-props.ts
- src/components/item/card/types/item-card-color.ts
- src/components/item/card/types/item-card-size.ts
- src/components/item/top-one-card/index.spec.tsx
- src/components/item/top-one-card/index.tsx
- src/components/item/top-one-card/skeleton.tsx
- src/components/item/top-one-card/stars.ts
- src/components/views/top-artists.tsx
- src/components/views/top-tracks.tsx
- src/pages/profile/last-tracks.tsx
- src/pages/profile/top-artists.tsx
- src/pages/profile/top-tracks.tsx
- src/sections/profile/last-tracks.tsx
> refactor(components): rename `element` -> `item`

- src/components/analysis/card.tsx
- src/components/common/index.ts
- src/components/common/open-in-spotify-button.tsx
- src/components/common/select-time-range.tsx
- src/components/profile/info.tsx
- src/components/views/top-artists.tsx
- src/components/views/top-tracks.tsx
- src/sections/profile/top-artists.spec.tsx
- src/sections/profile/top-genres.tsx
- src/sections/profile/top-tracks.spec.tsx
> Create array of analysis items and little code improvements

- src/components/common/infinite-loading-button.tsx
> fix(infinite-loading-button): spacing without icon

- app/components/common/relative-time.tsx
> fix(components/common/relative-time): add `suppressHydrationWarning` attribute to `p` element

- app/profile/top/template.tsx
> fix(profile/top/template): fix select view positioning on mobile

- app/api/fetchers/get-top-genres.spec.ts
- app/api/fetchers/get-top-genres.ts
- app/profile/page.tsx
- app/profile/sections/items.tsx
- app/profile/sections/recently-played.tsx
- app/profile/sections/top-artists.tsx
- app/profile/sections/top-genres.tsx
- app/profile/sections/top-items.tsx
- app/profile/sections/top-tracks.tsx
- app/profile/top/genres/page.tsx
- app/profile/types/profile-top-section-props.ts
- app/sections/default.tsx
> 106 implement fetching more genres in top genres page

- app/components/footer.tsx
- app/layout.tsx
> feat(components): create footer

- app/components/connect/button.tsx
- app/components/footer.tsx
- app/layout.tsx
- app/page.spec.tsx
- app/page.tsx
> feat(home): change landing page when logged in

- app/context/playback-state.spec.tsx
- app/context/playback-state.tsx
- app/profile/components/playback/card.tsx
> `PlaybackCard` change button icon immediatel y after click

- app/components/navigation/bar.tsx
> feat(navigation/bar): fix display name overflow and remove rigtch fm on mobile

- app/components/common/open-in-spotify-button.tsx
- app/profile/components/items/list.tsx
- app/profile/components/playback/card.spec.tsx
- app/profile/components/playback/card.tsx
> feat(playback/card): add relative time

- app/profile/components/playback/card.tsx
> fix(playback/card): static image width and height

- app/components/common/relative-time.spec.tsx
- app/profile/components/playback/card.spec.tsx
> feat(common/relative-time): add test coverage

- app/profile/[user-id]/layout.tsx
> fix(profile/layout): fix profile view

- app/not-found.tsx
- app/profile/[user-id]/not-found.tsx
> feat(home): add not found page

- app/components/ui/popover.tsx
- app/components/ui/toast.tsx
- app/components/ui/toaster.tsx
- app/components/ui/use-toast.ts
- app/layout.tsx
- app/profile/components/profile/card.tsx
- app/profile/components/profile/share-button.tsx
- package.json
- yarn.lock
> feat(profile): add share button

- app/components/cookies-dialog.tsx
- app/cookies-dialog.tsx
- app/layout.tsx
> feat(cookies-dialog): swap button placement

- app/profile/components/items/top-card.tsx
> fix(top-card): center name

- app/(items)/error.tsx
- app/profile/not-found.tsx
> feat(items): return not found page if error

- app/(items)/album/[album-id]/page.tsx
- app/api/types/album.ts
> feat(album): add date precision

- app/profile/components/items/top-card.tsx
- app/profile/components/profile/card.tsx
> feat(profile): fix open in spotify button width

- app/profile/components/items/item.tsx
- app/profile/components/items/top-card.tsx
> feat(profile/items): fix text width on smaller devices

- app/profile/components/playback/card.tsx
> feat(profile/playback/card): fix artists overflow

- app/(items)/album/[album-id]/page.tsx
- app/components/common/open-in-spotify-button.tsx
- app/profile/components/items/item.tsx
> feat(album): fix text dots

- app/(items)/album/[album-id]/page.tsx
- app/(items)/artist/[artist-id]/page.tsx
- app/(items)/track/[track-id]/page.tsx
- app/api/fetchers/get-artist-top-tracks.ts
- app/profile/components/items/item.tsx
- app/profile/components/items/list.tsx
- app/profile/sections/history.tsx
> feat(artist): add top artist tracks

- app/components/navigation/bar.tsx
> 254 hide rigtch logo on mobile and display hamburger

- .eslintrc.cjs
- app/components/common/select-view.spec.tsx
- app/components/common/toggle-time-range.spec.tsx
- app/components/footer.stories.tsx
- app/profile/components/playback/card.skeleton.tsx
- app/profile/components/playback/card.tsx
- app/profile/components/playback/index.ts
- app/profile/components/playback/toggle-state-button.spec.tsx
- app/profile/components/playback/toggle-state-button.stories.tsx
- app/profile/components/playback/toggle-state-button.tsx
- app/profile/components/profile/avatar.skeleton.tsx
- app/profile/components/profile/avatar.spec.tsx
- app/profile/components/profile/avatar.stories.tsx
- app/profile/components/profile/share-button.spec.tsx
- app/profile/components/profile/share-button.stories.tsx
- app/profile/components/profile/share-button.tsx
- app/styles/globals.css
- tests/snapshots/avatar.spec.tsx.snap
- tests/snapshots/share-button.spec.tsx.snap
- tests/snapshots/toggle-state-button.spec.tsx.snap
> 319 document and test rest of the misc components

- app/components/items/list/items-list.tsx
- app/profile/components/playback/playback-card.tsx
- app/utils/get-image.ts
> feat: fix playback card image skeleton

- app/(items)/album/[album-id]/page.tsx
- app/api/types/album.ts
> feat(album/page): add copyright

- app/auth/actions/handle-sign-in.spec.ts
- app/auth/actions/handle-sign-out.spec.ts
- app/auth/utils/get-server-token.spec.ts
- app/auth/utils/get-server-user.spec.ts
> 351 test auth functions

- app/(items)/album/[album-id]/page.tsx
- app/(items)/artist/[artist-id]/page.tsx
- app/(items)/sections/index.ts
- app/(items)/sections/item-header.spec.tsx
- app/(items)/sections/item-header.stories.tsx
- app/(items)/sections/item-header.tsx
- app/(items)/track/[track-id]/page.tsx
- app/components/common/buttons/link-button.tsx
- app/components/items/misc/item-artists.tsx
- tests/snapshots/item-artists.spec.tsx.snap
- tests/snapshots/item-card.spec.tsx.snap
- tests/snapshots/item-header.spec.tsx.snap
- tests/snapshots/item-top-card.spec.tsx.snap
- tests/snapshots/items-list-element.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
- tests/snapshots/items.spec.tsx.snap
> 349 create unified section for items pages

- app/components/navigation/navigation-bar.tsx
- app/layout.tsx
- app/page.tsx
> feat(app/page): fix overlapping

- app/api/types/rigtch-stats-response.ts
- app/components/items/cards/item-top-card.spec.tsx
- app/components/items/cards/item-top-card.stories.tsx
- app/components/items/cards/item-top-card.tsx
- app/components/items/examples.ts
- app/components/items/genre/genre-chip.spec.tsx
- app/components/items/genre/genre-chip.stories.tsx
- app/components/items/genre/genre-chip.tsx
- app/components/items/list/items-list-element.spec.tsx
- app/components/items/list/items-list-element.stories.tsx
- app/components/items/list/items-list-element.tsx
- app/components/items/list/items-list.spec.tsx
- app/components/items/list/items-list.stories.tsx
- app/components/items/list/items-list.tsx
- app/components/items/props.ts
- app/profile/components/common/selects/select-stats-measurement.spec.tsx
- app/profile/components/common/selects/select-stats-measurement.tsx
- app/profile/sections/top-genres-section.stories.tsx
- app/profile/sections/top-genres-section.tsx
- tests/snapshots/genre-chip.spec.tsx.snap
- tests/snapshots/items-list-element.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
> feat: change playtime -> playTime

- app/components/sidebar/sidebar.tsx
- tests/snapshots/sidebar.spec.tsx.snap
> fix(components/sidebar): top albums page time range

- app/profile/[id]/@analysis/loading.tsx
- app/profile/[id]/@top/@albums/loading.tsx
- app/profile/[id]/@top/@artists/loading.tsx
- app/profile/[id]/@top/@genres/loading.tsx
- app/profile/[id]/@top/@tracks/loading.tsx
- app/profile/[id]/top/albums/loading.tsx
- app/profile/[id]/top/artists/loading.tsx
- app/profile/[id]/top/genres/loading.tsx
- app/profile/[id]/top/tracks/loading.tsx
- app/profile/sections/analysis-section.skeleton.tsx
- app/profile/sections/items-section.stories.tsx
- app/profile/sections/top-albums-section.skeleton.tsx
- app/profile/sections/top-artists-section.skeleton.tsx
- app/profile/sections/top-genres-section.skeleton.tsx
- app/profile/sections/top-tracks-section.skeleton.tsx
> refactor(skeletons): rename `SkeletonSection` -> `SectionSkeleton`

- app/profile/components/playback/playback-card.skeleton.tsx
- app/profile/components/playback/playback-card.tsx
> fix(playback-card.skeleton): image width

- app/profile/sections/items-section.tsx
- tests/snapshots/items-section.spec.tsx.snap
> fix(profile/sections/items): children width

- app/components/items/list/items-list-element.tsx
- tests/snapshots/items-list-element.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
- tests/snapshots/items-section.spec.tsx.snap
> fix(components/items/list/element): element height

- app/profile/[id]/top/layout.tsx
> fix(profile/top/layout): show stats measurement on top items total pages

- app/components/items/misc/item-name.tsx
- tests/snapshots/item-card.spec.tsx.snap
- tests/snapshots/item-name.spec.tsx.snap
- tests/snapshots/item-top-card.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
- tests/snapshots/items-section.spec.tsx.snap
> 407 fix top item card name width

- app/components/common/spotify-link.tsx
- app/components/items/cards/item-top-card.skeleton.tsx
- app/components/items/list/items-list-element.skeleton.tsx
- app/components/items/list/items-list-element.tsx
- app/components/items/list/items-list.skeleton.tsx
- tests/snapshots/item-card.spec.tsx.snap
- tests/snapshots/item-header-section.spec.tsx.snap
- tests/snapshots/items-list-element.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
- tests/snapshots/items-section.spec.tsx.snap
- tests/snapshots/playback-card.spec.tsx.snap
- tests/snapshots/profile-card.spec.tsx.snap
- tests/snapshots/spotify-link.spec.tsx.snap
> 411 improve skeletons

- app/profile/[id]/@analysis/page.tsx
> fix(profile/@analysis/page): reverse progress colors and fix tempo

- app/components/items/cards/item-top-card.skeleton.tsx
- app/components/navigation/navigation-bar.tsx
- app/profile/[id]/@top/@tracks/loading.tsx
- tests/snapshots/navigation-bar.spec.tsx.snap
> 435 fix skeletons on smaller devices

- app/(items)/artist/[id]/page.tsx
- app/components/items/cards/item-card.tsx
- tests/snapshots/item-card.spec.tsx.snap
> 466 fix items page

- .github/workflows/main.yml
- app/components/ui/card.tsx
- app/profile/[id]/reports/@listeningDays/page.tsx
- app/profile/[id]/reports/@listeningHours/page.tsx
- app/profile/[id]/reports/components/charts/index.ts
- app/profile/[id]/reports/components/charts/listening-days-chart.tsx
- app/profile/[id]/reports/components/charts/listening-hours-chart.tsx
- app/profile/[id]/reports/components/helpers/chart-tooltip-content-formatter.tsx
- app/profile/[id]/reports/components/helpers/index.ts
- app/profile/[id]/reports/components/index.ts
- app/profile/[id]/reports/components/listening-days-chart.tsx
- app/profile/[id]/reports/helpers/index.ts
- app/profile/[id]/reports/helpers/value-measurement-formatter.spec.ts
- app/profile/[id]/reports/helpers/value-measurement-formatter.ts
- app/profile/[id]/reports/helpers/week-days.ts
- app/profile/[id]/reports/layout.tsx
- app/profile/[id]/reports/sections/index.ts
- app/profile/[id]/reports/sections/report-section.tsx
- tests/snapshots/profile-card.spec.tsx.snap
> 495 listening hours section

- .github/workflows/main.yml
- .prettierrc
- app/components/items/cards/item-top-card.tsx
- app/components/items/helpers/format-items.ts
- app/components/items/helpers/index.ts
- app/components/items/list/items-list-element.tsx
- app/components/items/list/items-list.tsx
- app/profile/[id]/reports/@listeningDays/page.tsx
- app/profile/[id]/reports/@listeningHours/page.tsx
- app/profile/[id]/reports/@mostListenedItems/page.tsx
- app/profile/[id]/reports/components/cards/index.ts
- app/profile/[id]/reports/components/cards/stat-card.tsx
- app/profile/[id]/reports/components/charts/listening-days-chart.tsx
- app/profile/[id]/reports/components/charts/listening-hours-chart.tsx
- app/profile/[id]/reports/helpers/get-cursors.ts
- app/profile/[id]/reports/helpers/index.ts
- app/profile/[id]/reports/layout.tsx
- app/profile/[id]/reports/sections/report-section.tsx
- tests/snapshots/item-top-card.spec.tsx.snap
- tests/snapshots/items-list-element.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
- tests/snapshots/items-section.spec.tsx.snap
closes #498 
closes #497 
closes #496 
related #491
> 498 tracks section with total listened tracks

- app/components/common/progress-with-value-label.tsx
- app/profile/[id]/reports/@mostListenedGenres/page.tsx
- app/profile/[id]/reports/components/cards/stat-card.tsx
- app/profile/[id]/reports/components/charts/index.ts
- app/profile/[id]/reports/components/charts/most-listened-genres-chart.tsx
- app/profile/[id]/reports/components/helpers/chart-tooltip-content-formatter.tsx
- app/profile/[id]/reports/layout.tsx
- tests/snapshots/item-top-card.spec.tsx.snap
- tests/snapshots/items-list.spec.tsx.snap
- tests/snapshots/progress-with-value-label.spec.tsx.snap
> 507 most listened genres

- app/profile/[id]/reports/@listeningDays/page.tsx
- app/profile/[id]/reports/@listeningHours/page.tsx
- app/profile/[id]/reports/@mostListenedGenres/page.tsx
- app/profile/[id]/reports/@mostListenedItems/page.tsx
> 510 catch if no data on reports

- app/profile/[id]/reports/@listeningDays/page.tsx
- app/profile/[id]/reports/@listeningHours/page.tsx
- app/profile/[id]/reports/@mostListenedGenres/page.tsx
- app/profile/[id]/reports/@mostListenedItems/page.tsx
- app/profile/[id]/reports/components/cards/stat-card.spec.tsx
- app/profile/[id]/reports/components/cards/stat-card.stories.tsx
- app/profile/[id]/reports/components/charts/listening-days-chart.stories.tsx
- app/profile/[id]/reports/components/charts/listening-hours-chart.stories.tsx
- app/profile/[id]/reports/components/charts/most-listened-genres-chart.stories.tsx
- app/profile/[id]/reports/components/helpers/chart-tooltip-content-formatter.spec.tsx
- app/profile/[id]/reports/components/helpers/chart-tooltip-content-formatter.tsx
- app/profile/[id]/reports/components/reports-pagination.tsx
- app/profile/[id]/reports/helpers/index.ts
- app/profile/[id]/reports/helpers/validate-cursors.spec.ts
- app/profile/[id]/reports/helpers/validate-cursors.ts
- app/profile/[id]/reports/layout.tsx
- tests/snapshots/chart-tooltip-content-formatter.spec.tsx.snap
- tests/snapshots/stat-card.spec.tsx.snap
> 504 missing tests and stories for reports components

- app/profile/sections/top-genres-section.tsx
- app/sections/default-section.tsx
- tests/snapshots/items-section.spec.tsx.snap
- tests/snapshots/top-genres-section.spec.tsx.snap
> fix(profile): unify sections padding

- app/components/sidebar/sidebar-section-item.tsx
- tests/snapshots/sidebar-section-item.spec.tsx.snap
- tests/snapshots/sidebar.spec.tsx.snap
> fix(components/sidebar/section-item): comparing `href` and `pathname`

- app/components/items/cards/item-top-card.skeleton.tsx
> fix(components/items/top-card/skeleton): replace stars

- app/api/fetchers/reports/get-reports-listening-days.ts
- app/api/types/index.ts
- app/api/types/listening-days.ts
- app/profile/[id]/reports/@listeningDays/page.tsx
- app/profile/[id]/reports/components/charts/listening-days-chart.stories.tsx
- app/profile/[id]/reports/components/charts/listening-days-chart.tsx
- app/profile/[id]/reports/components/helpers/chart-tooltip-content-formatter.tsx
- app/profile/[id]/reports/helpers/validate-cursors.spec.ts
- tests/snapshots/chart-tooltip-content-formatter.spec.tsx.snap
> 524 apply new reports listeningdays response

- app/profile/[id]/reports/@mostListenedGenres/page.tsx
- app/profile/[id]/reports/components/reports-pagination.tsx
> 529 fix reports pagination

- app/profile/[id]/reports/@listeningDays/page.tsx
- app/profile/[id]/reports/@listeningHours/page.tsx
- app/profile/[id]/reports/@mostListenedGenres/page.tsx
- app/profile/[id]/reports/@mostListenedItems/page.tsx
- app/profile/[id]/reports/components/cards/stat-card.spec.tsx
- app/profile/[id]/reports/components/cards/stat-card.stories.tsx
- app/profile/[id]/reports/components/cards/stat-card.tsx
> 535 change mostlistenedgenre stat card size to xlarge

- app/profile/[id]/reports/@mostListenedItems/page.tsx
> refactor(profile/reports/mostlisteneditems): change card titles

- app/profile/[id]/layout.tsx
> fix(components/sidebar): set max width to `250px`

- app/components/common/buttons/see-more-button.tsx
- app/components/sidebar/sidebar-section-item.tsx
- app/components/ui/pagination.tsx
- app/profile/[id]/reports/components/reports-pagination.tsx
- app/profile/components/common/selects/select-stats-measurement.spec.tsx
- app/profile/components/common/selects/select-stats-measurement.tsx
- app/profile/components/common/selects/select-time-range.spec.tsx
- app/profile/components/common/selects/select-time-range.tsx
- app/profile/components/common/selects/select-view.spec.tsx
- app/profile/components/common/selects/select-view.tsx
- app/profile/components/common/toggle-stats-provider.tsx
> 560 add prefetch on links

- app/api/auth/disconnect/route.spec.ts
- app/api/auth/disconnect/route.ts
- middleware.spec.ts
- middleware.ts
> 519 signout in middleware if userid is undefined

- app/profile/[id]/page.tsx
- app/profile/sections/top-genres-section.skeleton.tsx
> 581 fix genres skeleton

- app/api/types/user.ts
- app/profile/[id]/@profile/page.tsx
- app/profile/components/profile/profile-card.stories.tsx
- app/profile/components/profile/profile-card.tsx
- next.config.js
- tests/snapshots/profile-card.spec.tsx.snap
> 588 display followers and following count on users profile

- app/api/actions/index.ts
- app/api/actions/revalidate-user.ts
- app/api/fetchers/fetch-api.ts
- app/api/fetchers/get-user-followers.ts
- app/api/fetchers/get-user.ts
- app/api/fetchers/index.ts
- app/api/fetchers/put-follow-user.ts
- app/api/fetchers/put-unfollow-user.ts
- app/api/hooks/index.ts
- app/api/hooks/use-toggle-following.tsx
- app/api/types/index.ts
- app/api/types/user-followers.ts
- app/api/types/user-following.ts
- app/profile/[id]/@profile/page.tsx
- app/profile/components/profile/profile-card.spec.tsx
- app/profile/components/profile/profile-card.tsx
- tests/snapshots/profile-card.spec.tsx.snap
> 597 profile follow button

- app/api/fetchers/get-user-following.ts
- app/api/fetchers/index.ts
- app/api/types/user-followers.ts
- app/api/types/user-following.ts
- app/profile/[id]/@profile/page.tsx
- app/profile/components/profile/profile-card.tsx
- tests/snapshots/profile-card.spec.tsx.snap
> 599 add follows you label to profile card

- app/api/fetchers/get-user.ts
- app/profile/[id]/@modal/components/followers-following-dialog.tsx
- app/profile/components/profile/profile-card.tsx
> 610 use replace instead of push in modal links and use router back

- app/profile/[id]/page.tsx
- app/profile/[id]/views/index.ts
- app/profile/[id]/views/total-report-view.tsx
- app/profile/sections/total-items-listened.tsx
> 619 add total listened playtime

- app/api/fetchers/reports/get-reports-genres-listening-days.ts
- app/api/fetchers/reports/get-reports-listening-days.ts
- app/api/fetchers/reports/get-reports-listening-hours.ts
- app/api/fetchers/reports/get-reports-total-albums.ts
- app/api/fetchers/reports/get-reports-total-artists.ts
- app/api/fetchers/reports/get-reports-total-genres.ts
- app/api/fetchers/reports/get-reports-total-playtime.ts
- app/api/fetchers/reports/get-reports-total-tracks.ts
- app/api/fetchers/stats/rigtch/get-rigtch-top-albums.ts
- app/api/fetchers/stats/rigtch/get-rigtch-top-artists.ts
- app/api/fetchers/stats/rigtch/get-rigtch-top-genres.ts
- app/api/fetchers/stats/rigtch/get-rigtch-top-tracks.ts
- app/api/helpers/base-before-param-factory.ts
- app/api/helpers/index.ts
- app/profile/[id]/top/artists/page.tsx
- app/profile/[id]/top/tracks/page.tsx
> 609 add before search param in stats get fetchers

- app/components/items/genre/genre-chip.tsx
- app/components/items/genre/genres-list.tsx
- app/components/items/genre/index.ts
- app/profile/[id]/layout.tsx
- app/profile/[id]/reports/components/cards/chart-card.tsx
- app/profile/[id]/reports/components/cards/index.ts
- app/profile/[id]/reports/components/cards/stat-card.tsx
- app/profile/[id]/reports/components/charts/genres-listening-days-chart.tsx
- app/profile/[id]/reports/components/charts/listening-days-chart.tsx
- app/profile/[id]/reports/components/charts/listening-hours-chart.tsx
- app/profile/[id]/reports/helpers/value-measurement-formatter.ts
- app/profile/[id]/reports/page.tsx
- app/profile/[id]/reports/views/listening-days-view.tsx
- app/profile/[id]/reports/views/listening-hours-view.tsx
- app/profile/[id]/reports/views/most-listened-genres-view.tsx
- app/profile/[id]/reports/views/most-listened-items-view.tsx
- app/profile/components/profile/profile-card.tsx
- app/profile/sections/top-genres-section.tsx
- tests/snapshots/genre-chip.spec.tsx.snap
- tests/snapshots/profile-card.spec.tsx.snap
- tests/snapshots/stat-card.spec.tsx.snap
- tests/snapshots/top-genres-section.spec.tsx.snap
> 639 improve reports page

- app/components/navigation/navigation-bar.spec.tsx
- app/components/navigation/navigation-bar.tsx
> fix(components/navigation/bar): hide hamburger menu on homepage
